### ISSUE TITLE
Resolve construction recipe

### ISSUE THREAD

**Issue by onacit** [ruediste/salta#6]
I'm trying to use salta-jsr330 with my unit testing. And I got
```
Cannot find construction recipe for com.github.jinahya.hello.HelloWorldDemo
	at com.github.ruediste.salta.standard.config.StandardInjectorConfiguration$ConstructionConfiguration.createConcreteConstructionRecipe(StandardInjectorConfiguration.java:164)
	at com.github.ruediste.salta.standard.binder.StandardBindingBuilderImpl.lambda$null$2(StandardBindingBuilderImpl.java:83)
	at com.github.ruediste.salta.standard.StandardStaticBinding.createRecipe(StandardStaticBinding.java:31)
	at com.github.ruediste.salta.core.Binding.lambda$getOrCreateRecipe$0(Binding.java:43)
	at com.github.ruediste.salta.core.RecipeCreationContextImpl.withBinding(RecipeCreationContextImpl.java:55)
	at com.github.ruediste.salta.core.Binding.getOrCreateRecipe(Binding.java:37)
	at com.github.ruediste.salta.standard.config.DefaultScope.createRecipe(DefaultScope.java:18)
	at com.github.ruediste.salta.core.StaticBindingSet.lambda$apply$0(StaticBindingSet.java:76)
	at com.github.ruediste.salta.core.CoreInjector$1$1.apply(CoreInjector.java:209)
	at com.github.ruediste.salta.core.CoreInjector$1$1.apply(CoreInjector.java:206)
	at com.github.ruediste.salta.core.RecipeCreationContextImpl.lambda$tryGetRecipe$0(RecipeCreationContextImpl.java:100)
	at java.util.Optional.map(Optional.java:215)
	at com.github.ruediste.salta.core.RecipeCreationContextImpl.tryGetRecipe(RecipeCreationContextImpl.java:100)
	at com.github.ruediste.salta.standard.util.MembersInjectorFactoryBase.createMembersInjectors(MembersInjectorFactoryBase.java:57)
	at com.github.ruediste.salta.standard.config.StandardInjectorConfiguration$ConstructionConfiguration.createRecipeMembersInjectors(StandardInjectorConfiguration.java:257)
	at com.github.ruediste.salta.standard.util.MembersInjectorCreationRuleBase.getMembersInjectionRecipe(MembersInjectorCreationRuleBase.java:71)
	at com.github.ruediste.salta.standard.util.MembersInjectorCreationRuleBase.getMembersInjectorNoCache(MembersInjectorCreationRuleBase.java:47)
	at com.github.ruediste.salta.standard.util.MembersInjectorCreationRuleBase.getMembersInjector(MembersInjectorCreationRuleBase.java:40)
	at com.github.ruediste.salta.standard.util.MembersInjectorCreationRuleBase.lambda$apply$0(MembersInjectorCreationRuleBase.java:99)
	at com.github.ruediste.salta.core.CoreInjector$1$1.apply(CoreInjector.java:209)
	at com.github.ruediste.salta.core.CoreInjector$1$1.apply(CoreInjector.java:206)
	at com.github.ruediste.salta.core.CoreInjector.lambda$null$3(CoreInjector.java:164)
	at java.util.Optional.map(Optional.java:215)
	at com.github.ruediste.salta.core.CoreInjector.lambda$tryGetRecipe$4(CoreInjector.java:164)
	at com.github.ruediste.salta.core.CoreInjector.withRecipeCreationContext(CoreInjector.java:135)
	at com.github.ruediste.salta.core.CoreInjector.tryGetRecipe(CoreInjector.java:164)
	at com.github.ruediste.salta.core.CoreInjector.tryGetCompiledRecipe(CoreInjector.java:110)
	at com.github.ruediste.salta.core.CoreInjector.getInstance(CoreInjector.java:61)
	... 60 more
```
I really don't have any idea for resolving this by myself. Do I need any annotation process for so called `constructor recipe`s?

Thanks.

**Comment by ruediste** [comment]
Hi

How does the constructor of your class look like? If it had parameters, you
need to put an @Inject. See
https://github.com/ruediste/salta/wiki/JustInTimeBindings#eligible-constructors

Regards

Ruedi
